CREATE DATABASE IF NOT EXISTS `__database_name__`;
USE `__database_name__`;

CREATE TABLE IF NOT EXISTS users(id INT PRIMARY KEY AUTO_INCREMENT, nick VARCHAR(254) NOT NULL);

CREATE TABLE IF NOT EXISTS entities(id INT PRIMARY KEY AUTO_INCREMENT, name VARCHAR(254) NOT NULL, c_date DATE NOT NULL DEFAULT CURRENT_DATE, c_time TIME NOT NULL DEFAULT CURRENT_TIME, m_date DATE NOT NULL DEFAULT CURRENT_DATE, m_time TIME NOT NULL DEFAULT CURRENT_TIME, cord_x FLOAT NOT NULL DEFAULT 200, cord_y FLOAT NOT NULL DEFAULT 200);
CREATE TABLE IF NOT EXISTS entity_properties(id INT PRIMARY KEY AUTO_INCREMENT, entity_id INT NOT NULL, name VARCHAR(254) NOT NULL, type VARCHAR(1) NOT NULL, data TEXT NOT NULL, cord_x FLOAT NOT NULL DEFAULT 200, cord_y FLOAT NOT NULL DEFAULT 200);